version: '3'
services:
  web:
    build: .
    env_file:
      - .env
    environment:
      - FLASK_DEBUG=1
      - FLASK_ENV=development
      # (OPTIONAL) Over write Zartan Appliction Template settings.
      #  eg. 'admin', 'b2b', 'dealer', 'ecommerce', 'finance', 'healthcare', etc. Details: https://bit.ly/2Vxo1BB
      - APP_TEMPLATE=healthcare
    ports:
      - '8666:8666'
    volumes:
      - .:/app